### PR TITLE
plant to region scraper created

### PR DESCRIPTION
**Pull request by cchchoi1986**

### CODE REVIEW

**Comment by cchchoi1986** [comment]
@paulld @harrychenca

**Comment by h8rry** [comment]
Make sure your indentations are correct. Doesn't look right here: https://github.com/cchchoi1986/hikehk/blob/back-end/identify-plantsregions/lib/tasks/make_region_plants.rake

Also, don't have unnecessary line breaks. 

Code looks good. You should merge if you are comfortable :)

**Comment by cchchoi1986** [comment]
hey Harry, not sure what you mean by unneccessary line breaks or indents; can't find them.  Although I see Cassie is running a 4 space per tab whereas mine is a two space.  I'll conform to her standard now on

**Comment by h8rry** [comment]
Line breaks
screen shot 2015-02-21 at 10 26 55 am

You should have fixed the tab size on your end before you merge.

**Comment by cassiemak** [comment]
Clement I should be running a 2 space tab wor....  Hmmm

**Pull request merged**
