### PR TITLE
Back end/database setup

### PR DESCRIPTION
**Pull request by cchchoi1986**

### CODE REVIEW

**Comment by cchchoi1986** [comment]
@harrychenca @paulld @cassiemak

**Comment by h8rry** [comment]
Did you merge both #20 and #21 without rebasing?

**Comment by cassiemak** [comment]
He says, they are fairly different things and thus didn't need to rebase.
haha

**Comment by h8rry** [comment]
I am comparing between https://github.com/cchchoi1986/hikehk/pull/21/files and https://github.com/cchchoi1986/hikehk/pull/20/files. These file changes look exactly the same to me

**Pull request merged**
